# Generated by Django 3.1.3 on 2021-06-24 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 5, 18, 24, 956598, tzinfo=utc)),
        ),
    ]
