# Generated by Django 3.1.3 on 2021-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210624_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='some text', max_length=300),
            preserve_default=False,
        ),
    ]
